name: Azure App Service - memory-api(Production), Build and deploy NodeJS app

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: memory-api
        slot-name: Production
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d7d30234f3384f25bb7d898dd9b1f923 }}
        package: .
